name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: ~

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Install wasm-tools
      run: |
        dotnet workload install wasm-tools
    - name: Build
      run: dotnet build -c Release
    - name: Publish
      run: dotnet publish -c Release
    - name: Fix _framework
      run: |
        mv TubeLess/bin/Release/net8.0/publish/wwwroot/_framework TubeLess/bin/Release/net8.0/publish/wwwroot/framework
        sed -i 's/_framework/framework/g' TubeLess/bin/Release/net8.0/publish/wwwroot/index.html
        sed -i 's/_framework/framework/g' TubeLess/bin/Release/net8.0/publish/wwwroot/framework/blazor.webassembly.js
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './TubeLess/bin/Release/net8.0/publish/wwwroot'

  deploy:
    needs: build_and_upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
